spring:
  datasource:
    # Usando os nomes exatos que aparecem no seu print do Railway
    url: jdbc:mysql://${RAILWAY_PRIVATE_DOMAIN}:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect