spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Na produção, ele vai buscar essas variáveis que você vai criar no painel do Railway
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}